### PR TITLE
Fix database warning about already started transaction

### LINKED ISSUE #16: SQLConnection.commit()/rollback() causes WARNING: there is already a transaction in progress
The implementation of `commit()`:

    override def commit(handler: Handler[AsyncResult[Void]]): SQLConnection = {
      if (inTransaction) {
        inTransaction = false
        connection.sendQuery("COMMIT") flatMap (_ => connection.sendQuery("BEGIN")) onComplete doneVoid(handler)
      } else {
        handler.handle(VFuture.failedFuture("Not in a transaction currently"))
      }
      this
    }

I believe the problem is that `inTransaction` remains `false` after the connection sends a `BEGIN` to the database, which messes up the behaviour of `beginTransactionIfNeeded` and `close`, etc. Same problem exists in `rollback`

### PR DESCRIPTION
**Pull request by Narigo**
Should fix #16 . I have no idea how to test the database log of Postgres here, but I could see the warning go away after using the new test `makeTwoTransactionsAfterEachOther`.

### CODE REVIEW

File: src/test/scala/io/vertx/ext/asyncsql/SQLTestBase.scala [hunk 1]
```diff
@@ -279,9 +295,9 @@ abstract class SQLTestBase extends VertxTestBase with TestData {
       conn <- f
       _ <- arhToFuture(conn.close _)
     } yield {
-      log.info("closed connection -> done")
-      testComplete()
-    }) recover {
+        log.info("closed connection -> done")
```
Comment (purplefox) [inline src/test/scala/io/vertx/ext/asyncsql/SQLTestBase.scala]: log.info

**Comment by Narigo** [comment]
Removed the `log.info`.
